config/routes.rb
Rails.application.routes.draw do

  resources :articles

   # AUTHENTICATION

  # This route sends requests to our naked url to the *cool* action in the *gif* controller.
  root to: 'gif#cool'

  # I've created a gif controller so I have a page I can secure later.
  # This is optional (as is the root to: above).
  # get '/cool' => 'gif#cool'

  # These routes will be for signup. The first renders a form in the browse, the second will
  # receive the form and create a user in our database using the data given to us by the user.
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  # These routes are for showing users a login form, logging them in, and logging them out.
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
  end

  def edit
  end

  def update
    # @task.update(params[:task]) => not secure, that´s why we implement the private task_params method so no additional inputs can be passed in the form
    @article.update(article_params)

    redirect_to article_path(@article)
    #redirect_to task_path(id: task.id) => old school
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
  # strong param against hackers

  def find_article
     @article = Article.find(params[:id])
  end
end

app/controllers/gif_controller.rb
class GifController < ApplicationController

  before_action :authorize

  def cool
  end

  def free
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if @user && @user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = @user.id
      redirect_to root_path
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash[:error] = "An error occured!"

        redirect_to signup_path
        # render 'new'
      end
    end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/gif_helper.rb
module GifHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title  %>
  <%= f.label :content, "Content" %>
  <%= f.text_field :content  %>
  <%= f.submit %>
<% end %>

app/views/articles/create.html.erb
<h2> Article was succesfully created</h2>

<h2><%= @article.title %> </h2>
<p> <%= link_to "Edit", edit_article_path(@article) %> </p>
<p> <%= link_to "Delete", article_path(@article), method: :delete %> </p>

<p><%= @article.content %></p>

app/views/articles/edit.html.erb
<h1> Editing article </h1>


<%= render 'form' %>

<p> <%= link_to "Show", article_path(@article) %> </p>
<p> <%= link_to "Back", articles_path %> </p>

app/views/articles/index.html.erb
<h1> <%= link_to "Wikinimous", articles_path  %> </h1>

<%= link_to "New article", new_article_path %>

  <% @articles.each do |article| %>
    <h2> <%= link_to article.title, article_path(article) %> </h2>
    <p><%= article.content %></p>
  <% end  %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<p> <%= link_to "Back", articles_path %> </p>

app/views/articles/show.html.erb
<h2><%= @article.title %> </h2>
<p> <%= link_to "Edit", edit_article_path(@article) %> </p>
<p> <%= link_to "Delete", article_path(@article), method: :delete %> </p>

<p><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <% if current_user %>
      Signed in as <%= current_user.name %> | <%= link_to "Logout", logout_path %>
  <% else %>
      <%= link_to 'Login', login_path %> | <%= link_to 'Signup', signup_path %>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: users_path do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>